### ISSUE TITLE
opening for only once

### ISSUE THREAD

**Issue by Kasugi** [Trsak/esx_inventoryhud_trunk#12] opened 2019-05-07 23:57 UTC
when I bought a car and try to open trunk inventory its opening for only once I cant open second time

**Comment by KingRyuShin** [comment] 2019-05-08 21:23
that is because when you buy a vehicle you have to logout and log back in so it's really registered to you and it will work great

**Comment by XxFri3ndlyxX** [comment] 2019-05-09 02:06
You could try changing from 
`local closecar = GetClosestVehicle(x, y, z, 4.0, 0, 71)`
and 
`local closecar = GetClosestVehicle(x, y, z, 4.0, 0, 70)`
TO
`local closecar = GetClosestVehicle(x, y, z, 4.0, 0, 127)`

**Comment by Kasugi** [comment] 2019-05-09 13:13
Okay ı will try this

9 May 2019 Per 05:06 tarihinde XxFri3ndlyxX <notifications@github.com> şunu
yazdı:

**Comment by DJJeffP** [comment] 2019-05-18 03:49
### I had these errors on my server side:

[ERROR] [MySQL] [esx_inventoryhud_trunk] An error happens on MySQL for query "[object Object]": ER_DUP_ENTRY: Duplicate entry 'YQD 257 ' for key 'UNIQUE'
Error: (node:8512) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
    at process.<anonymous> (internal/process/promises.js:27:25)
    at <anonymous>
    at Query.db.query [as _callback] (mysql-async.js:4973:13)
    at Query.Sequence.end (mysql-async.js:280:24)
    at Query.ErrorPacket (mysql-async.js:2122:8)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
Error: (node:8512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Error: (node:8512) UnhandledPromiseRejectionWarning: Error: ER_DUP_ENTRY: Duplicate entry 'YQD 257 ' for key 'UNIQUE'
    at Query.Sequence._packetToError (mysql-async.js:244:14)
    at Query.ErrorPacket (mysql-async.js:2109:18)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (mysql-async.js:4728:23)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4985:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:8512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

### And these on my Console.log:
![esx_inventoryhud_trunk_ error](https://user-images.githubusercontent.com/50760233/57964114-0291a000-7930-11e9-85d8-e730f72ab528.png)


I think I found a solution for this error after some searching on google, but please correct me if I am wrong. 
I deleted in MySQL database the:

  UNIQUE KEY 'plate' ('plate') 

And now its working fine for me. But it's tested with only one player and one vehicle in the database.

> refer to https://stackoverflow.com/questions/11638505/1062-duplicate-entry-for-key-primary

**Comment by DJJeffP** [comment] 2019-05-18 05:29
The issue is I think the pNotify that is blocking your inventory of your trunk.
try this in client/esx_trunk-cl.lua to see if this helps and check also with F8 for Console log.


          if ESX.UI.Menu.IsOpen("default", GetCurrentResourceName(), "inventory") then
            SetVehicleDoorShut(vehFront, 5, false)
          else
            if locked == 1 or class == 15 or class == 16 or class == 14 then
              SetVehicleDoorOpen(vehFront, 5, false, false)
              ESX.UI.Menu.CloseAll()

              if globalplate ~= nil or globalplate ~= "" or globalplate ~= " " then
                CloseToVehicle = true
                OpenCoffreInventoryMenu(GetVehicleNumberPlateText(vehFront), Config.VehicleLimit[class], myVeh)
              end
            else
              print("\n---------------------------------------------------")
              print("This trunk is locked")
              ESX.ShowNotification(_U"trunk_closed")
              -- exports.pNotify:SendNotification
              -- {
              --     text = _U("trunk_closed"),
              --     type = "error",
              --     timeout = 3000,
              --     layout = "bottomCenter",
              --     queue = "trunk"}
              -- )
            end
          end
        else
          print("\n---------------------------------------------------")
          print("There is no vehicle nearby.")
          ESX.ShowNotification(_U"no_veh_nearby")
          -- exports.pNotify:SendNotification(
          --   {
          --     text = _U("no_veh_nearby"),
          --     type = "error",
          --     timeout = 3000,
          --     layout = "bottomCenter",
          --     queue = "trunk"
          --   }
          -- )
        end
        lastOpen = true
        GUI.Time = GetGameTimer()
      end
    else
      -- Not their vehicle
      print("\n---------------------------------------------------")
      print("This is not your vehicle.")
      ESX.ShowNotification(_U"nacho_veh")
      -- exports.pNotify:SendNotification(
      --   {
      --     text = _U("nacho_veh"),
      --     type = "error",
      --     timeout = 3000,
      --     layout = "bottomCenter",
      --     queue = "trunk"
      --   }
      -- )
    end

After changing you trunk should function normal.

But there is also an other error in the script:

[ERROR] [MySQL] [esx_inventoryhud_trunk] An error happens on MySQL for query "[object Object]": ER_DUP_ENTRY: Duplicate entry 'YQD 257 ' for key 'UNIQUE'
Error: (node:20484) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
    at process.<anonymous> (internal/process/promises.js:27:25)
    at <anonymous>
    at Query.db.query [as _callback] (mysql-async.js:4973:13)
    at Query.Sequence.end (mysql-async.js:280:24)
    at Query.ErrorPacket (mysql-async.js:2122:8)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
Error: (node:20484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
Error: (node:20484) UnhandledPromiseRejectionWarning: Error: ER_DUP_ENTRY: Duplicate entry 'YQD 257 ' for key 'UNIQUE'
    at Query.Sequence._packetToError (mysql-async.js:244:14)
    at Query.ErrorPacket (mysql-async.js:2109:18)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (mysql-async.js:4728:23)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4985:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:20484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)

Who can help me with that one?

> Duplicate entry 'platenumberhere ' for key 'UNIQUE'. 

I think that error is correct because it's already in the database and the colum 'plate' is a unique colum so no duplicates allowed. So we need somekind of an backup for this, but I don't know where.

**Comment by DJJeffP** [comment] 2019-05-18 05:44
Little update. I hard restarted my fivem client and server programs (close both programs and reopened it) and now my MySQL error is gone so I think its solved on my side now with the 

> Duplicate entry 'platenumberhere ' for key 'UNIQUE'.

so I think the error was still in my cache. :-(

**Comment by XenSide** [comment] 2019-05-18 18:57
> Little update. I hard restarted my fivem client and server programs (close both programs and reopened it) and now my MySQL error is gone so I think its solved on my side now with the
> 
> > Duplicate entry 'platenumberhere ' for key 'UNIQUE'.
> 
> so I think the error was still in my cache. :-(
> 
> But still we need to backup that error ;-)

This is not what's happening, this isn't a cache error or anything like that.

The script creates a new record in your database every time you open the trunk of a car which is not owned by you (NPC cars for example) without checking if the plate of that vehicle was previously registered or not, so basically what happens is that your DB tries to Insert the new record in your table but a record with the same primary key alredy exists and throws an error, this is quite serious and might need to be one of the first things to get fixed.


@Trsak

**Comment by Kasugi** [comment] 2019-05-19 00:23
> You could try changing from
> `local closecar = GetClosestVehicle(x, y, z, 4.0, 0, 71)`
> and
> `local closecar = GetClosestVehicle(x, y, z, 4.0, 0, 70)`
> TO
> `local closecar = GetClosestVehicle(x, y, z, 4.0, 0, 127)`

I tried its work for 2-3 time and it wont work again.

**Comment by DJJeffP** [comment] 2019-05-19 14:32
@kasugi install pNotify and you will be good. See my post earlyer here. If already installed then please supply us some more information like consol log (F8 in game) or server log (fivem server)So we can beter help you.

**Comment by Trsak** [comment] 2020-09-11 16:27
Closing since I have released new reworked version.

**Closed by Trsak** 2020-09-11 16:27 UTC
